import type { ProjectInput, TenderPreferences } from '@/types/project'

const defaultTenderPreferences: TenderPreferences = {
  tone: 'procurement-ready',
  length: 'detailed',
  includeMandatory: true,
  includeOptional: true,
  includeEvaluationCriteria: true,
  includeAcceptanceTests: true,
  includeDeliverables: true,
  includeMilestones: true,
  includeServiceLevels: true,
  includeSecurityRequirements: true,
  includeSupportRequirements: true,
  includeLockInClauses: true,
  includeReferenceExamples: false,
  includeDelegationPlan: true,
}

/** A blank project to back a fresh intake form. */
export function createEmptyProject(): ProjectInput {
  return {
    projectTitle: '',
    organisation: '',
    background: '',
    problemStatement: '',
    intendedUsers: [],
    userPainPoints: '',
    businessOutcomes: [],
    projectStage: 'pilot',
    timeline: '',
    expectedUsers: '',
    departmentsInvolved: '',
    useCases: [],
    customUseCase: '',
    dataSources: [],
    dataTypes: [],
    dataCadence: 'not-specified',
    deploymentPreference: 'not-specified',
    dataSensitivity: 'not-specified',
    aiCapabilities: [],
    modelStrategy: [],
    architecturePriorities: [],
    securityRequirements: [],
    performanceRequirements: {},
    tenderPreferences: { ...defaultTenderPreferences },
  }
}

/**
 * The fictitious scenario the app ships with and loads by default. Replaces any
 * real client example so nothing project-specific is published. Northwind Building
 * Society is a fictional mutual — a citation-grounded support copilot for its staff.
 */
export const DEFAULT_PROJECT: ProjectInput = {
  ...createEmptyProject(),
  projectTitle: 'Member Support Knowledge Copilot',
  organisation: 'Northwind Building Society',
  background:
    'Contact-centre agents and branch staff answer member questions by searching across product terms and conditions, lending policies, complaint-handling procedures and regulatory guidance held in disconnected systems and intranets.',
  problemStatement:
    'There is no single, trustworthy way to ask a question and receive an accurate, up-to-date answer with the source passage, so answers vary between agents and onboarding new staff is slow.',
  intendedUsers: ['Contact-centre agents', 'Branch staff', 'Compliance reviewers'],
  userPainPoints:
    'Slow searching across scattered sources, inconsistent answers between agents, uncertainty about which policy version is current, and no audit trail for what was told to a member.',
  businessOutcomes: [
    'Faster, more consistent member query resolution',
    'Answers grounded in the current, approved source',
    'Reduced agent onboarding time',
    'Auditable, compliant responses',
  ],
  projectStage: 'production',
  timeline: '9 months',
  expectedUsers: '1,200',
  departmentsInvolved: '6',
  useCases: ['RAG chatbot', 'Document search and summarisation', 'Decision support system'],
  dataSources: ['Knowledge bases', 'Unstructured documents', 'Internal systems', 'Historical records'],
  dataTypes: ['PDFs', 'Office documents', 'Structured records'],
  dataCadence: 'batch',
  deploymentPreference: 'hybrid',
  dataSensitivity: 'high',
  aiCapabilities: [
    'Retrieval-augmented generation',
    'Question answering',
    'Citation-grounded answers',
    'Summarisation',
    'Classification',
    'Human-in-the-loop review',
    'Confidence scoring',
    'Audit trails',
    'Embeddings',
    'Reranking',
  ],
  modelStrategy: [
    'Hybrid hosted and self-hosted',
    'Model gateway required',
    'Separate embedding, reranking, and generation models',
    'Fallback model required',
    'Need to avoid vendor lock-in',
  ],
  architecturePriorities: [
    'Vendor agnostic',
    'Security',
    'Auditability',
    'Data sovereignty',
    'High availability',
    'Modular replacement of components',
  ],
  securityRequirements: [
    'Identity and access management',
    'Role-based access control',
    'Data encryption at rest',
    'Data encryption in transit',
    'Audit logging',
    'Prompt and response logging',
    'Content safety',
    'Compliance requirements',
  ],
  performanceRequirements: {
    concurrentUsers: '300',
    dailyQueryVolume: '25,000',
    documentCorpusSize: '120',
    documentCorpusUnit: 'GB',
    availabilityTarget: '99.5%',
    rto: '1 hour',
    rpo: '15 minutes',
  },
}

export interface Preset {
  id: string
  name: string
  summary: string
  input: ProjectInput
}

export const PRESETS: Preset[] = [
  {
    id: 'member-support-copilot',
    name: 'Member Support Knowledge Copilot',
    summary: 'Citation-grounded support copilot for member-facing staff (default sample).',
    input: structuredClone(DEFAULT_PROJECT),
  },
  {
    id: 'rag-chatbot',
    name: 'RAG Chatbot for Internal Documents',
    summary: 'Citation-grounded chatbot over internal documents and knowledge bases.',
    input: {
      ...createEmptyProject(),
      projectTitle: 'Internal Knowledge Assistant',
      organisation: 'Corporate Services Division',
      background:
        'Staff spend significant time searching policy documents, manuals and historical records across disconnected repositories.',
      problemStatement:
        'There is no single, trustworthy way to ask questions of internal documentation and receive answers with verifiable sources.',
      intendedUsers: ['Internal staff', 'Knowledge managers', 'Administrators'],
      userPainPoints: 'Slow document search, inconsistent answers, no source traceability.',
      businessOutcomes: ['Faster information access', 'Reduced support load', 'Consistent, sourced answers'],
      projectStage: 'production',
      timeline: '6 months',
      expectedUsers: '2,000',
      departmentsInvolved: '5',
      useCases: ['RAG chatbot', 'Document search and summarisation'],
      dataSources: ['Unstructured documents', 'Knowledge bases', 'Historical records'],
      dataTypes: ['PDFs', 'Office documents'],
      dataCadence: 'batch',
      deploymentPreference: 'hybrid',
      dataSensitivity: 'high',
      aiCapabilities: [
        'Retrieval-augmented generation',
        'Question answering',
        'Summarisation',
        'Citation-grounded answers',
        'Embeddings',
        'Reranking',
        'Audit trails',
      ],
      modelStrategy: [
        'Hybrid hosted and self-hosted',
        'Model gateway required',
        'Separate embedding, reranking, and generation models',
        'Need to avoid vendor lock-in',
      ],
      architecturePriorities: ['Vendor agnostic', 'Security', 'Auditability', 'Modular replacement of components'],
      securityRequirements: [
        'Identity and access management',
        'Role-based access control',
        'Data encryption at rest',
        'Data encryption in transit',
        'Audit logging',
        'Prompt and response logging',
      ],
      performanceRequirements: {
        concurrentUsers: '200',
        dailyQueryVolume: '10,000',
        documentCorpusSize: '250',
        documentCorpusUnit: 'GB',
      },
    },
  },
  {
    id: 'industrial-copilot',
    name: 'Industrial Copilot for Operations',
    summary: 'Agentic operations assistant with human-in-the-loop and integrations.',
    input: {
      ...createEmptyProject(),
      projectTitle: 'Operations Planning Copilot',
      organisation: 'Industrial Operations',
      background:
        'Operations teams coordinate planning across maintenance, scheduling and field systems using fragmented tools.',
      problemStatement:
        'Operators lack a single assistant that can reason over operational data and trigger approved actions safely.',
      intendedUsers: ['Operations users', 'Planners', 'Approvers'],
      userPainPoints: 'Manual coordination, slow decisions, limited visibility across systems.',
      businessOutcomes: ['Faster planning cycles', 'Fewer errors', 'Auditable decisions'],
      projectStage: 'pilot',
      timeline: '9 months',
      expectedUsers: '500',
      departmentsInvolved: '3',
      useCases: ['Operations planning assistant', 'Agentic workflow automation', 'Decision support system'],
      dataSources: ['Internal systems', 'Sensor data', 'APIs', 'Unstructured documents', 'Real-time telemetry'],
      dataTypes: ['Structured records', 'Sensor / time-series', 'PDFs'],
      dataCadence: 'both',
      deploymentPreference: 'hybrid',
      dataSensitivity: 'high',
      aiCapabilities: [
        'Agent workflows',
        'Tool calling',
        'Planning and reasoning',
        'Retrieval-augmented generation',
        'Human-in-the-loop review',
        'Audit trails',
        'Confidence scoring',
      ],
      modelStrategy: [
        'Hybrid hosted and self-hosted',
        'Model gateway required',
        'Fallback model required',
        'Routing across multiple model providers',
      ],
      architecturePriorities: [
        'Vendor agnostic',
        'High availability',
        'Auditability',
        'Interoperability',
        'Security',
      ],
      securityRequirements: [
        'Role-based access control',
        'Human approval workflow',
        'Audit logging',
        'Policy guardrails',
        'Network segmentation',
      ],
      performanceRequirements: {
        concurrentUsers: '150',
        dailyQueryVolume: '5,000',
        rto: '1 hour',
        rpo: '15 minutes',
      },
    },
  },
  {
    id: 'self-hosted-serving',
    name: 'Self-Hosted Model-Serving Platform',
    summary: 'Open, GPU-backed, self-hosted serving platform with endpoint switching.',
    input: {
      ...createEmptyProject(),
      projectTitle: 'Model-Serving Platform',
      organisation: 'AI Platform Engineering',
      background:
        'The organisation needs a controlled, self-hosted platform to serve interchangeable models for multiple applications.',
      problemStatement:
        'Applications are coupled to specific model providers, making it hard to switch models or control cost and latency.',
      intendedUsers: ['Platform engineers', 'Application teams', 'Operations users'],
      userPainPoints: 'Vendor coupling, unpredictable cost, limited control over latency.',
      businessOutcomes: ['Provider independence', 'Lower latency', 'Higher throughput'],
      projectStage: 'enterprise',
      timeline: '12 months',
      expectedUsers: '50 internal teams',
      departmentsInvolved: '8',
      useCases: ['Model-serving platform'],
      dataSources: ['APIs', 'Internal systems'],
      dataTypes: ['Structured records'],
      dataCadence: 'real-time',
      deploymentPreference: 'on-premises',
      dataSensitivity: 'restricted',
      aiCapabilities: ['Text generation', 'Embeddings', 'Reranking', 'Evaluation and benchmarking', 'Audit trails'],
      modelStrategy: [
        'Self-hosted model',
        'GPU-backed serving',
        'CPU-only fallback',
        'Multiple interchangeable model providers',
        'Model gateway required',
        'Routing across multiple model providers',
        'Need to switch vendors easily',
        'Need to avoid vendor lock-in',
      ],
      architecturePriorities: [
        'Open source preference',
        'Vendor agnostic',
        'Low latency',
        'High throughput',
        'Scalability',
        'Modular replacement of components',
      ],
      securityRequirements: [
        'Identity and access management',
        'Role-based access control',
        'Secret management',
        'Audit logging',
        'Network segmentation',
        'Private connectivity',
      ],
      performanceRequirements: {
        concurrentUsers: '1,000',
        dailyQueryVolume: '1,000,000',
        rto: '30 minutes',
        rpo: '5 minutes',
      },
    },
  },
  {
    id: 'multimodal-doc-intelligence',
    name: 'Multimodal Document Intelligence',
    summary: 'Multimodal understanding of PDFs, scans and forms with human review.',
    input: {
      ...createEmptyProject(),
      projectTitle: 'Document Intelligence Platform',
      organisation: 'Records & Compliance',
      background:
        'Large volumes of scanned documents, forms and diagrams require extraction, understanding and verification.',
      problemStatement:
        'Manual processing of mixed-format documents is slow, error-prone and hard to audit.',
      intendedUsers: ['Records officers', 'Reviewers', 'Approvers'],
      userPainPoints: 'Manual data entry, inconsistent extraction, weak auditability.',
      businessOutcomes: ['Faster processing', 'Higher accuracy', 'Auditable extraction'],
      projectStage: 'production',
      timeline: '8 months',
      expectedUsers: '800',
      departmentsInvolved: '4',
      useCases: ['Computer vision and multimodal AI', 'Document search and summarisation'],
      dataSources: ['Unstructured documents', 'Document repositories', 'Historical records'],
      dataTypes: ['PDFs', 'Scanned documents', 'Images', 'Diagrams'],
      dataCadence: 'batch',
      deploymentPreference: 'on-premises',
      dataSensitivity: 'restricted',
      aiCapabilities: [
        'Document understanding',
        'Image understanding',
        'Multimodal input',
        'Citation-grounded answers',
        'Summarisation',
        'Classification',
        'Human-in-the-loop review',
        'Audit trails',
      ],
      modelStrategy: [
        'Hybrid hosted and self-hosted',
        'Model gateway required',
        'Separate embedding, reranking, and generation models',
        'Need to avoid vendor lock-in',
      ],
      architecturePriorities: [
        'Vendor agnostic',
        'Auditability',
        'Security',
        'Data sovereignty',
        'Modular replacement of components',
      ],
      securityRequirements: [
        'Role-based access control',
        'Data encryption at rest',
        'Data encryption in transit',
        'Audit logging',
        'Human approval workflow',
        'Sensitive data handling',
      ],
      performanceRequirements: {
        concurrentUsers: '100',
        dailyQueryVolume: '20,000',
        documentCorpusSize: '2',
        documentCorpusUnit: 'TB',
      },
    },
  },
]
